# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

apt_packages:
  - libv8-dev

r:
 - oldrel
 - release
 - devel

<<<<<<< HEAD
notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "irc.rud.is#builds"
    nick: travisci

after_success:
  - Rscript -e 'covr::codecov()'
=======
after_success:
  - Rscript -e 'covr::codecov()'
>>>>>>> c0ce51942c79090d1a9ae3fb95f7e2b292d9302e
