# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

apt_packages:
  - libv8-dev

r:
 - oldrel
 - release
 - devel

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "irc.rud.is#builds"
    nick: travisci
